<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/js/bui/skin/red/css/dpl.css">
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/js/bui/skin/red/css/bui.css">
    <title>用户管理</title>
</head>
<body>
<div class="container">
    <form class="form-horizontal">
        <div class="row" style="margin-top: 20px;">
            <div class="control-group span7">
                <label class="control-label">用户编号</label>
                <div class="controls"><input class="input-normal control-text"/></div>
            </div>
            <div class="control-group span7">
                <label class="control-label">帐号关键字</label>
                <div class="controls"><input class="input-normal control-text"/></div>
            </div>
            <div class="span6">
                <button id="search-button" class="button-info">搜索</button>
            </div>
        </div>
    </form>
    <hr/>
    <div id="user-grid" style="margin:10px;"></div>
</div>
<!-- JS -->
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery/jquery-1.11.0.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/bui/skin/red/seed-min.js"></script>
<script type="text/javascript">
    var baseUrl="<?php echo $this->baseUrl(); ?>";
</script>
<script type="text/javascript">
    BUI.use(['bui/data','bui/grid','bui/overlay','bui/form'],function(Data,Grid,Overlay,Form){
        var addForm,editForm,addDialog,editDialog,store,columns,grid;
        store=new Data.Store({
            url:baseUrl+'/core/user/list',
            proxy:{
                method:'POST'
            }
        });
        columns=[{
            title:'用户编号',dataIndex:'id',width:100,elCls:'center'
        },{
            title:'账户名',dataIndex:'uname',width:150,elCls:'center'
        },{
            title:'用户组',dataIndex:'usergroup',width:100,elCls:'center'
        },{
            title:'当前状态',dataIndex:'valid'
        },{
            title:'操作',elCls:'center',renderer:function(value,obj){
                return '<span class="grid-command edit-handler">编辑</span>';
            }
        }];
        grid=new Grid.Grid({
            render:'#user-grid',
            //width:510,
            columns:columns,
            loadMask:true,
            store:store,
            plugins:[Grid.Plugins.RowNumber],
            tbar:{
                items:[{
                    btnCls:'button button-small',
                    text:'新增',
                    listeners:{
                        click:function(){
                            //
                        }
                    }
                }]
            },
            autoRender:true
        });
        $('#search-button').bind('click',function(){
            alert('OK');
        });
    };
</script>
</body>
</html>