<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>管理用户组管理</title>
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/blueprint/grid.css" type="text/css" media="screen, projection" />
    <style type="text/css">
        .l-table-edit { }
        .l-table-edit-td { padding:4px; }
    </style>
</head>
<body>
<div class="container" style="margin-top:20px;">
    <div class="span-24 last">
        <div id="role-grid"></div>
    </div>
</div>
<!-- 新增用户框 -->
<div id="add-dialog" style="display:none;">
    <div>
        <table cellpadding="0" cellspacing="0" class="l-table-edit" >
            <tr>
                <td align="right" class="l-table-edit-td"><label>用户组代码</label></td>
                <td align="left" class="l-table-edit-td"><input type="text" id="af1"/></td>
            </tr>
            <tr>
                <td align="right" class="l-table-edit-td"><label>用户名组名称</label></td>
                <td align="left" class="l-table-edit-td"><input type="text" id="af2"/></td>
            </tr>
            <tr>
                <td align="right" class="l-table-edit-td"><label>详情描述</label></td>
                <td align="left" class="l-table-edit-td"><textarea id="af3"></textarea></td>
            </tr>
            <tr>
                <td align="right" class="l-table-edit-td"><label>是否有效</label></td>
                <td align="left" class="l-table-edit-td"><input type="text" id="af4"/></td>
            </tr>
        </table>
    </div>
</div>
<!-- 编辑用户框 -->
<div id="edit-dialog" style="display:none;">
    <div>
        <table cellpadding="0" cellspacing="0" class="l-table-edit" >
            <tr>
                <td align="right" class="l-table-edit-td"><label>用户组代码</label></td>
                <td align="left" class="l-table-edit-td"><input type="text" id="ef1"/></td>
            </tr>
            <tr>
                <td align="right" class="l-table-edit-td"><label>用户名组名称</label></td>
                <td align="left" class="l-table-edit-td"><input type="text" id="ef2"/></td>
            </tr>
            <tr>
                <td align="right" class="l-table-edit-td"><label>详情描述</label></td>
                <td align="left" class="l-table-edit-td"><textarea id="ef3"></textarea></td>
            </tr>
            <tr>
                <td align="right" class="l-table-edit-td"><label>是否有效</label></td>
                <td align="left" class="l-table-edit-td"><input type="text" id="ef4"/></td>
            </tr>
        </table>
    </div>
</div>

<script type="text/javascript">
    var baseUrl='<?php echo $this->baseUrl();?>';
</script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/js/mikoUI/skins/mikoui-icons.css" />
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery/jquery-1.11.0.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/cookie/jquery.cookie.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/sys/client.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/mikoUI/js/mikoui.all.js"></script>
<script type="text/javascript">
    $(function(){
        var g;
        $('#role-grid').mikoGrid({
            url:baseUrl+'/core/role/list',
            width:450,
            columns:[{
                display:'角色代码',name:'rf1',width:150
            },{
                display:'用户组名称',name:'rf2',width:150
            },{
                display:'状态',name:'rf3',width:100,render:function(rowdata,rowindex,value){
                    return value=='1' ? '有效' : '无效';
                }
            }],
            toolbar:{
                items:[{
                    text: '新增',
                    icon: 'add',
                    click:function(){
                        $.mikoDialog.open({
                            target:$('#add-dialog'),
                            title:'新增用户组',
                            buttons:[{
                                text:'确认提交',
                                cls:'l-dialog-btn-highlight',
                                onclick:function(item,dialog){
                                    var av1=$.trim(miko.get('af1').getValue());
                                    var av2=$.trim(miko.get('af2').getValue());
                                    var av3=$.trim($('#af3').val());
                                    var av4=miko.get('af4').getValue();
                                    if(!/^[A-Z]{2}$/.test(av1)){
                                        $.mikoDialog.error('用户组代码必须为两位大写字母');
                                        return;
                                    }
                                    if(av2=='' || av2.length>10){
                                        $.mikoDialog.error('未填写用户组名称或字数过长');
                                        return;
                                    }
                                    if(av3.length>100){
                                        $.mikoDialog.error('用户组描述字数过长');
                                        return;
                                    }
                                    if(av4==''){
                                        $.mikoDialog.error('请选择用户组初始状态');
                                        return;
                                    }
                                    $.post(baseUrl+'/core/role/add',{
                                        av1:av1,
                                        av2:av2,
                                        av3:av3,
                                        av4:av4
                                    },function(data){
                                        if(data.success){
                                            $.mikoDialog.success(data.info);
                                            g.reload();
                                            miko.get('af1').setValue('');
                                            miko.get('af2').setValue('');
                                            $('#af3').val('');
                                            miko.get('af4').setValue('');
                                            dialog.hide();
                                        }else{
                                            $.mikoDialog.error(data.info);
                                        }
                                    });
                                }
                            },{
                                text:'取消',
                                onclick:function(item,dialog){
                                    dialog.hide();
                                }
                            }]
                        });
                    }
                },{
                    line:true
                },{
                    text: '编辑',
                    icon: 'modify',
                    click:function(){
                        var selection= g.getSelected();
                        if(selection){
                            var code=selection.rf1;
                            $.post(baseUrl+'/core/role/detail',{code:code},function(data){
                                if(data){
                                    miko.get('ef1').setValue(data.rf1);
                                    miko.get('ef2').setValue(data.rf2);
                                    $('#ef3').val(data.rf3);
                                    miko.get('ef4').setValue(data.rf4);
                                    $.mikoDialog.open({
                                        target:$('#edit-dialog'),
                                        title:'编辑用户组',
                                        buttons:[{
                                            text:'确认提交',
                                            cls:'l-dialog-btn-highlight',
                                            onclick:function(item,dialog){
                                                var ev1=miko.get('ef1').getValue();
                                                var ev2=$.trim(miko.get('ef2').getValue());
                                                var ev3=$.trim($('#ef3').val());
                                                var ev4=miko.get('ef4').getValue();
                                                if(ev2=='' || ev2.length>10){
                                                    $.mikoDialog.error('未填写用户组名称或字数过长');
                                                    return;
                                                }
                                                if(ev3.length>100){
                                                    $.mikoDialog.error('用户组描述字数过长');
                                                    return;
                                                }
                                                if(ev4==''){
                                                    $.mikoDialog.error('请选择用户组初始状态');
                                                    return;
                                                }
                                                $.post(baseUrl+'/core/role/edit',{
                                                    ev1:ev1,
                                                    ev2:ev2,
                                                    ev3:ev3,
                                                    ev4:ev4
                                                },function(data){
                                                    if(data.success){
                                                        $.mikoDialog.success(data.info);
                                                        g.reload();
                                                        dialog.hide();
                                                    }else{
                                                        $.mikoDialog.error(data.info);
                                                    }
                                                });
                                            }
                                        },{
                                            text:'取消',
                                            onclick:function(item,dialog){
                                                dialog.hide();
                                            }
                                        }]
                                    });
                                }
                            });
                        }else{
                            $.mikoDialog.warn('请选择用户组');
                        }
                    }
                },{
                    line:true
                },{
                    text: '版块权限设置',
                    icon: 'settings',
                    click:function(){

                    }
                },{
                    line:true
                },{
                    text: '详情',
                    icon: 'attibutes',
                    click:function(){

                    }
                }]
            }
        });
        g=$('#role-grid').mikoGetGridManager();
        /**
         * 新增用户组框
         */
        $('#af1').mikoTextBox({
            width:150
        });
        $('#af2').mikoTextBox({
            width:150
        });
        $('#af4').mikoComboBox({
            width:100,
            cancelable:false,
            data:[{id:'1',text:'是'},{id:'0',text:'否'}]
        });
        /**
         * 编辑用户组框
         */
        $('#ef1').mikoTextBox({
            width:150,
            disabled:true
        });
        $('#ef2').mikoTextBox({
            width:150
        });
        $('#ef4').mikoComboBox({
            width:100,
            cancelable:false,
            data:[{id:'1',text:'是'},{id:'0',text:'否'}]
        });
    });
</script>
</body>
</html>