<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>门户管理后台</title>
</head>
<body>
<div id="wrapper">
    <div id="frametop" position="top">
        <h3>头部LOGO</h3>
    </div>
    <div id="frameleft" position="left" title="导航菜单">
        <?php foreach($this->menus as $menuItem): ?>
        <div title="<?php echo $menuItem->mname; ?>">
            <ul class="tree_nav" mid="<?php echo $menuItem->mid; ?>"></ul>
        </div>
        <?php endforeach; ?>
    </div>
    <div id="framecenter" position="center">

    </div>
</div>

<script type="text/javascript">
    var baseUrl='<?php echo $this->baseUrl();?>';
    var menusObj=eval('<?php echo $this->menusJSON;?>');
    var menus={};
    for(var i=0;i<menusObj.length;i++){
        menus['item'+menusObj[i].mid]=menusObj[i].forums;
    }
</script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery/jquery-1.11.0.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/plugins/cookie/jquery.cookie.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/sys/client.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/mikoUI/js/mikoui.all.js"></script>
<script type="text/javascript">
    $(function(){
        $('#wrapper').mikoLayout({
            topHeight:80,
            allowTopResize:false,
            leftWidth:250,
            minLeftWidth:200
        });
        $('#frameleft').mikoAccordion({});
        var tab=null;
        var mid,url,pid,fid,text;
        $('.tree_nav').each(function(i){
            mid=$(this).attr('mid');
            tree=$(this).mikoTree({
                nodeWidth:150,
                data:eval('menus.item'+mid),
                idFieldName:'fid',
                parentIDFieldName:'pid',
                textFieldName:'fname',
                checkbox:false,
                onClick:function(data,target){
                    url=data.data.url;
                    pid=data.data.pid || 0;
                    fid=data.data.fid || 0;
                    text=data.data.fname;
                    if(url){
                        f_addtab(pid+'_'+fid,text,baseUrl+url);
                    }
                }
            });
            tree.collapseAll();
        });
        $('#framecenter').mikoTab({});
        tab=miko.get('framecenter');

        function f_addtab(tabid,text,url){
            tab.addTabItem({
                tabid: tabid,
                text: text,
                url: url,
                height:650,
                callback: function () {}
            });
        }
    });
</script>
</body>
</html>